apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: cilium-bgp
spec:
 virtualRouters:
 - localASN: 65512
   exportPodCIDR: true
   neighbors:
    - peerAddress: 127.0.0.1/32
      peerASN: 65128
